#####################################
#   Name: Joseph Coffa              #
#   Student #: 1007320              #
#   Due Date: February 4, 2019      #
#                                   #
#   Assignment 1, CIS*2750          #
#   Makefile                        #
#####################################

CC = gcc
FLAGS = -std=c11 -Wall -Wpedantic
EXECFLAGS = -g

# TODO shared libraries
#all: list parser


main: CalendarParser.h LinkedListAPI.h
	$(CC) $(FLAGS) $(EXECFLAGS) -o main

#############
# Utilities #
#############
clean:
	rm bin/* main
