#####################################
#   Name: Joseph Coffa              #
#   Student #: 1007320              #
#   Due Date: February 4, 2019      #
#                                   #
#   Assignment 1, CIS*2750          #
#   Makefile                        #
#####################################

CC = gcc
FLAGS = -std=c11 -Wall -Wpedantic
EXECFLAGS = -g
VPATH = src:include:bin:..
LIBS = CalendarParser.h LinkedListAPI.h Parsing.h Comparison.h



#############
# Utilities #
#############
clean:
	rm bin/* main
