# FIXME THIS IS A TEMPORARY MAKEFILE SINCE WE DON'T KNOW HOW TO COMPILE SHARED
# LIBRARIES YET, AND I HAVE TO HARDOCDE PATHS IN INCLUDE STATEMENTS
# This makefile is useless after figuring the above out, and is meant to be obsolete.

main:
	gcc -std=c11 -Wall -Wpedantic -g *.c -o main
